// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnsvVUV6XVk2wRSZ7pt3ADIemuH6NlI2Q',
    appId: '1:658802182930:web:0029785bbe0420ab6bc1cb',
    messagingSenderId: '658802182930',
    projectId: 'netlearn-3f933',
    authDomain: 'netlearn-3f933.firebaseapp.com',
    databaseURL: 'https://netlearn-3f933-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'netlearn-3f933.firebasestorage.app',
    measurementId: 'G-PGX2996QSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9T1wNWysIOjdbS36iJ-Ivg8Q9eWS5eo',
    appId: '1:658802182930:android:1731e14428fb60ba6bc1cb',
    messagingSenderId: '658802182930',
    projectId: 'netlearn-3f933',
    databaseURL: 'https://netlearn-3f933-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'netlearn-3f933.firebasestorage.app',
  );
}
